### ISSUE TITLE
Sats Contributions Append vs Starting at 0

### ISSUE THREAD

**Issue by jimBeaux27** [stakwork/sphinx-ios#100]
Expected: when I edit the sats contribution amount, I should start at 0 or "" by default
Actual: It simply appends whatever I'm typing and can lead to a mistake like 100k sats instead of intended 100 sats

**Comment by jimBeaux27** [comment]
@tomastiminskas can you take a peak at the PR when you get a chance so we can close this out?

**Comment by tomastiminskas** [comment]
I took a look at it, but wasn't sure what was the expected behavior. Did you discuss this with @pitoi ??

**Comment by jimBeaux27** [comment]
@tomastiminskas yes it was Paul that actually pointed it out to me.

**Comment by tomastiminskas** [comment]
Perfect, then I will merge it and include it in next release
