### ISSUE TITLE
Doesn't Sync my Subscriptions Between Devices

### ISSUE THREAD

**Issue by jimBeaux27** [stakwork/sphinx-ios#107]
If I log in with Device A and get all my subscriptions in order, they don't carry over to Device B.

Expectation: If I subscribe to a new pod on Device A, when I login on Device B it should be in my followed feed.
Reality: I have to go resubscribe or enter a chat linked to the pod in order to get Device B to take on the subscription

Maybe the expectation is not in the spec but may be worthwhile putting in a future spec as people may expect that.

**Comment by pitoi** [comment]
Agreed, this should sync btw all devices.
