### ISSUE TITLE
App Crashes when Switching to Feeds Tab

### ISSUE THREAD

**Issue by jimBeaux27** [stakwork/sphinx-ios#109]
1. Run the app
2. Go to background for a few minutes
3. Click the Feed tab
4. App Crashes

**Comment by pitoi** [comment]
I'm using build 295 from testflight but unable to recreate this issue. By background, do you mean let the phone go to sleep or just switch to another app?

**Comment by jimBeaux27** [comment]
I'm giving a rough heuristic b/c it's something I noticed several times this weekend. The pattern I noticed was:
1. App is in background (switched to home screen or other app)
2. At least maybe 10 minutes to marinate in that state

Tough to recreate but rest assured, I will with debugger connected.

**Comment by pitoi** [comment]
I was able to recreate this by tapping on the "All" button under the Feed. I submitted the crash report. The app was in the background, phone awake, for a few minutes.

**Comment by pitoi** [comment]
This may be a separate bug, but I'm able to crash the app by switching through the sections under Feed.
 - tap Feed
 -  tap, listen > watch > then "All"
 
https://user-images.githubusercontent.com/814886/210192818-2fc12bd0-78ff-4033-ae15-1f8d9bf3e8d0.mov

**Comment by jimBeaux27** [comment]
It seems like it might be related. I will do a deep dive...Also when I observed it I sent the feedback to the developer. Where can we check those logs?

**Comment by pitoi** [comment]
@tomastiminskas usually reviews the crash reports, we can get you setup when he's back

**Comment by jimBeaux27** [comment]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/96802642/210260595-068fb86a-96e8-4667-8c5c-e72650d307c6.png">
<img width="947" alt="image" src="https://user-images.githubusercontent.com/96802642/210260728-d390b803-1c12-438c-b1d2-02cd5ea36b3e.png">

@tomastiminskas here are the related crash reports that I sent/annotated related to the bug in question. I suspect that there may be some issue with indexing/reindexing of the feed OR there's an issue updating the UI. I think we might have to make sure that when we update the UI for that screen we do so from the main thread. I've seen crashes like this when failing to do so.

**Comment by jimBeaux27** [comment]
@tomastiminskas i took a simple stab at this with this: https://github.com/jimBeaux27/sphinx-ios/tree/jc/develop/fix-feed-view-crash. This is very difficult to recreate. It seems like when I'm attached to my debugger I am not able to but I will keep trying. I think it is either an issue with updating the UI from a non-main thread or from the indexes changing in the collectionview and us not handling it well. Let's review when you get back

**Comment by jimBeaux27** [comment]
I haven't seen this one since recent updates. Is it ok if I close it @tomastiminskas @pitoi ?
