### ISSUE TITLE
Publish app source-code in this repo

### ISSUE THREAD

**Issue by emanuelb** [stakwork/sphinx-ios#13]
This repo is "empty" and contain only README.md file, please publish the source code for the latest Sphinx app on apple store in this repo, which currently is Version 1.0.23 last updated: 7 May 2021
https://apps.apple.com/ie/app/sphinx-chat/id1483956418

**Comment by emanuelb** [comment]
Source code was published for older version 1.0.10:
https://github.com/stakwork/sphinx-ios/blob/1b1670113c2ac6fecee9d10917fdb1d7f57e8966/sphinx.xcodeproj/project.pbxproj#L3946

which is the first version on Apple Store from 17 Jan 2021, but the current version is 1.0.23 last updated: 7 May 2021, please publish the source-code for the latest version.

**Comment by cd2357** [comment]
+1

Same for [sphinx-mac](https://github.com/stakwork/sphinx-mac)
