### ISSUE TITLE
Sphinx desktop: notifications

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-ios#133]
Even with "Banner" Selected, I'm getting audio notices when new messages come into sphinx and the app is in the background

<img width="340" alt="Screen Shot 2023-02-02 at 11 03 21 AM" src="https://user-images.githubusercontent.com/814886/216406244-47083525-4060-4b71-8f2a-fb7c1567eac7.png">

**Comment by tomastiminskas** [comment]
After android I'm planning to work on Mac again: 
- Podcast player refactor (took from the work I did on iOS)
- Content Feed Status sync changes

I will do this ticket and any other pending fixes on Mac at that time

**Comment by jimBeaux27** [comment]
@pitoi I moved this to the mac board just to keep it organized
