### ISSUE TITLE
New msg indicator

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-ios#146]
The new feature that retains chat view at the last viewed msg is working great, but the "new msg" indicator is missing so it's not clear that new items are available if the user scrolls down.

**Comment by tomastiminskas** [comment]
Can you specify what do you mean by "new msg" indicator? are you referring to the blue circle with new msgs count in chat list? Or something inside the chat view itself?

**Comment by jimBeaux27** [comment]
@tomastiminskas I think he means the little green icon + arrow that points down

**Comment by tomastiminskas** [comment]
This is fixed already. We discussed with Paul about it in sphinx.
