### ISSUE TITLE
Improve Pin UX

### ISSUE THREAD

**Issue by jimBeaux27** [stakwork/sphinx-ios#149]
Entering pin is onerous. Let's improve:
- Allow for a "never" option for pin timeout
- Change pin timeout default never
- FaceID get it working

**Comment by tomastiminskas** [comment]
@jimBeaux27 just one thing to fix. I had my PIN time set to 24 hours (maximum value). When I launched the app from this branch and went to Profile it was set to Never requiere PIN. Seems like as it was on the maximum value before, it will show after upgrade on the maximum value (which is NEVER required PIN) even when the logic will keep the old configuration of 24 hours (I guess). 

You need to test running from current test-flight state, then running with these new changes
