### ISSUE TITLE
Pre-cache first few minutes of the top most likely podcasts

### ISSUE THREAD

**Issue by jimBeaux27** [stakwork/sphinx-ios#161]
- Check option to pre load content using AVPlayer or iOS libraries
- Research about the possibility of creating mp3 clips from the first 10/15 seconds of each episode and store them in S3 so then we can start playing that small clip and then switch to the episode file

**Comment by jimBeaux27** [comment]
done by @tomastiminskas

**Comment by tomastiminskas** [comment]
@jimBeaux27 I wouldn't close it yet. I did some changes to preload the items, but let's test and see how it works. We might need to keep improving this or trying different approaches.
