### ISSUE TITLE
Show episodes description

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-ios#171]
Find a place in the UI to show entire episode description

**Comment by Antanasijevic** [comment]
![image](https://user-images.githubusercontent.com/13258550/228638881-470e24ec-539c-400e-9cdf-711ecf4fee8d.png)

**Comment by Antanasijevic** [comment]
@tomastiminskas Final Instructions and Link to final design can be found in new ticket #186 . I think you can close this ticket.
