### ISSUE TITLE
hardware signer first time signup - swarm

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-ios#189]
Right now the app needs access to your Profile page to setup hardware device.

But before the hardware is linked, CLN has no pubkey. Thus relay has no admin Contact record, and cannot sign up. 

We can either:
- show "link hardware" on the first onboarding screen
- change relay to not require an initial pubkey / Contact for signing up

@pitoi what do you think?

**Comment by pitoi** [comment]
I lean toward allowing relay to talk to the app before we get the pubkey, then generate the keys on hardware and launch CL or CLN through relay
