### ISSUE TITLE
Failed payments in transactions list

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-ios#195]
As we will start tracking failed payments in relay (payments inside chat, key send payments from dashboard, streaming sats payments when consuming feed content, etc) we need a way to show them in the transactions list. 

![IMG_0983](https://user-images.githubusercontent.com/2242281/233048869-24378137-22d8-43e6-819a-6ab3f362a658.PNG)

We should implement a new UI for failed payment rows. 

- This will apply just to outgoing payment. 
- It should include an optional error message

**Comment by Antanasijevic** [comment]
@pitoi Failed payment can expand to reveal additional notes about the error.
This may be an opportunity to add few layout adjustments. 
Boxed icons for sent and received payment maybe work better in the list. Also, do we still need icons for receipt?
Please, let me know what you think

![image](https://user-images.githubusercontent.com/13258550/235495824-16d629df-eaee-4d93-929d-4d7db9144161.png)

**Comment by Antanasijevic** [comment]
@pitoi Here is updated version of transaction list, with failed payments, and tribe messages, with stakes in expandable view.

https://user-images.githubusercontent.com/13258550/235991064-5d96b18a-4761-4ec4-847e-c3da3f08686e.mp4
