### ISSUE TITLE
Podcast player notes

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-ios#204]
1. it seems that only shows that I'm subscribed to show up in the Recently played list. I searched for a podcast, played the episode, then played a different one. There's no way I can find to get back to the last one played. 
Categories for All: 
 - Following
 - Recently Played
 Listen:
 - Listen Now
 - Following
This is up for discussion, but we need to make these consistent. 

2. The artwork shows in the app, but not on the lockscreen. Other podcast shows do have artwork displayed.
This is on build 334

![IMG_BB89BA75CDCC-1](https://user-images.githubusercontent.com/814886/234685611-dd6c2041-db1f-4218-8783-7d59fe314e0e.jpeg)

**Comment by jimBeaux27** [comment]
Thanks Paul I'll take a look regarding the recently played.

Regarding the no album artwork can you confirm your iOS version so I can try to recreate?

**Comment by jimBeaux27** [comment]
@pitoi @tomastiminskas I was able to make a quick PR that will just show you the last consumed ocntent even if it's not subscribed to in the "All" tab.

I see your point about keeping consistency across all tabs. Should I use the same methodology to as on the All tab? Personally I feel this experiment with recently listened was a big success b/c I'm able to more easily find the content I want fast.

**Comment by jimBeaux27** [comment]
NVM I am able to recreate the artwork problem. I suspect it has something to do with the odd parameters The Verge tends to pass to their album artwork URLs

**Comment by jimBeaux27** [comment]
@pitoi I went ahead and made all feed tabs follow the paradigm of:
Recently Published/Released
Recently Listened/Watched/Read

I think this is a superior way to organize things aligned with the way Spotify does things & I respect the way they do their UX.
