### ISSUE TITLE
Manage Storage [Final Design]

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-ios#221]
**Figma project with instructions**

https://www.figma.com/file/L1oq8hh8kYU90bQxPAin3G/Mobile-Design-System---Dark-Version?type=design&node-id=5619%3A11020&t=VwT6xZERVWoelNYp-1

-------------------------

**Figma Prototypes**

Dark Skin
https://www.figma.com/proto/L1oq8hh8kYU90bQxPAin3G/Mobile-Design-System---Dark-Version?type=design&node-id=5619-11366&scaling=min-zoom&page-id=5619%3A11020&starting-point-node-id=5619%3A11366&show-proto-sidebar=1

Light Skin
https://www.figma.com/proto/L1oq8hh8kYU90bQxPAin3G/Mobile-Design-System---Dark-Version?type=design&node-id=5628-13713&scaling=min-zoom&page-id=5619%3A11020&starting-point-node-id=5628%3A13713&show-proto-sidebar=1

----------------------------
If you need help finding right page inside Figma project, or need help with prototype, please check out our ["General Instructions"](https://github.com/stakwork/sphinx/issues/234) page.

For more detailed instructions, please check out ["Figma for developers" ](https://www.figma.com/best-practices/tips-on-developer-handoff/an-overview-of-figma-for-developers/)page.

---------------------

Video 

https://github.com/stakwork/sphinx-ios/assets/13258550/02fc218b-c584-47ab-8b73-a440a311681d

**Comment by tomastiminskas** [comment]
This is implemented. We can re open if we need to do changes/improvements in the future
