### ISSUE TITLE
Expand Storage Management to Files & Audio

### ISSUE THREAD

**Issue by uncleJim21** [stakwork/sphinx-ios#223]
We did the first pass now it's time to account for a couple more permutations:
- Voice/audio files users pass to each other
- General purpose files that don't fall nicely into the existing buckets

Some suggestions for what this might entail:
1. A new fourth classification outside of Audio, Video, Images that has its own color code & gets added to the existing list
2. A method for visually representing these new cases in the "Chat Media" selector/manager view. I am thinking something like a microphone with the ability to actually playback the recording if it's an audio/vocie file or file icon for those that do not fall nicely into the existing buckets (suppose its a pdf, an exe, a dmg, a .doc an xls, etc)

**Comment by Antanasijevic** [comment]
@uncleJim21 Do you have any suggestion how can we show list of general files? 
The simplest way may be showing a file name with a small extension icon (PDF, DOC...). 
Tap on a file name would open it.
We can also go with a thumbnail preview of a file but not sure if that is practical in this case.
What do you think?

**Comment by Antanasijevic** [comment]
https://github.com/stakwork/sphinx-ios/assets/13258550/0ca369ae-aa6e-406c-bffc-88e2a76f34f7
