### ISSUE TITLE
Media support on threads

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-ios#260]
Right now we don't allow to send media on threads, we just support starting a thread from an attachment message.

We will start supporting sending media on threads.

1. Start sending thread_uuid on send attachment endpoint as we do on send message endpoint. That needs to be done on 2 cases: 
    - When replying to a message with a media file on tribe chat
    - When sending an attachment inside a thread

2. We should adapt the UI of the thread row to show media on last reply if last reply contains attachment (show designs with Milan)

**Comment by Antanasijevic** [comment]
Final Layouts are in this Figma project. I have moved Layouts for replies with media into separate page, so you can find it more easily. I have also posted a comment marking exact page you should use.

Pages you should use are: 
- Replies with Media (Dark Skin)
- Replies with Media (Light Skin)

https://www.figma.com/file/L1oq8hh8kYU90bQxPAin3G/Mobile-Design-System---Dark-Version?type=design&node-id=6515%3A13113&mode=design&t=bwEILuaPXDzX9CvE-1

**Comment by tomastiminskas** [comment]
This is implemented. We can re open if we need to do changes/improvements in the future
