### ISSUE TITLE
Mobile signer security updates

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-ios#265]
BOTH for kotlin and swift

Drop the HDWalletKit or whatever library you are currently using

Instead, just generate 32 bytes on the phone and store that securely (this is your "entropy" or "seed"). These 32-bytes hex-encoded can be sent into `sphinx.mnemonic_from_entropy` to return the seed phrase that can be shown to the user. The same seed bytes are what are used to run `sphinx.node_keys` to generate your private/public key pair

**Comment by Evanfeenstra** [comment]
Also, we should enable SSL.

If the port is 1883, then DO NOT add any SSL verification. But if the port is NOT 1883 (could be a domain name with no port at all), then you need to enable SSL

[](https://github.com/emqx/CocoaMQTT#ssl-secure)
](https://github.com/emqx/CocoaMQTT#ssl-secure)

For now you can just set `mqtt.allowUntrustCACertificate = true` for testing... but you could also figure out "real" ssl (it shows how in the CocoaMQTT readme)

**Comment by uncleJim21** [comment]
ok. Looking at the recommended method here:
openssl pkcs12 -export -clcerts -in client-cert.pem -inkey client-key.pem -out client.p12

It appears that it is possible to run CLI code from inside a Swift application but I'd have to figure out with you how exactly to generate/obtain the 2 inputs. I assume the client-key would just be the publickey correct?

**Comment by Evanfeenstra** [comment]
> ok. Looking at the recommended method here: openssl pkcs12 -export -clcerts -in client-cert.pem -inkey client-key.pem -out client.p12
> 
> It appears that it is possible to run CLI code from inside a Swift application but I'd have to figure out with you how exactly to generate/obtain the 2 inputs. I assume the client-key would just be the publickey correct?

You dont need to run that inside the app... its something to run in your terminal and then provide the p12 file to the app. But lets start with the easier `mqtt.allowUntrustCACertificate = true`. Although it does not provide 2-way authentication, it does still mean that the payload is encrypted and so we avoid man-in-the-middle attacks

**Comment by uncleJim21** [comment]
Oh so the p12 would be generated one time and stored in the app somehow? Not sure exactly how that would work. I assumed each user would generate unique keys
