### ISSUE TITLE
sphinx signup

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-ios#269]
- there was an alert saying "Signer Setup Required" or something like that when you clicked New User. That's not right... there can be lite users who do not need to setup a signer. Instead go straight to the QR scanner
    - if QR action=glyph then they need to choose "hardware" or "mobile signer". The "relay" field in the QR should be saved in order to do the admin signup flow
        - if hardware is chosen, the the QR fields should pre-fill the CLN url and the network alert fields
        - if mobile signer is chosen, then those fields should be used for the MQTT setup
    - or action might = connect .. or there is a different hub invite mode too i think...

**Comment by uncleJim21** [comment]
"there can be lite users who do not need to setup a signer"

I think you may mean the dedicated node workflow right? I think the lite node is the green button that directs them to Lite mode (which seems to be disabled?)

**Comment by Evanfeenstra** [comment]
> "there can be lite users who do not need to setup a signer"
> 
> I think you may mean the dedicated node workflow right? I think the lite node is the green button that directs them to Lite mode (which seems to be disabled?)

yes, dedicated node workflow as well. However there can also be lite user who has a `connect::RELAY_IP::PUBKEY` code
