### ISSUE TITLE
Unable to tap link in first thread message

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-ios#279]
**Task**

If a user has sent a link/url tribe message that has turned into a thread, when reading the thread, the link is not able to be tapped.

**Steps to recreate**

- Send a tribe message with a url link
- Turn message into a thread by responding or having someone else respond
- View thread, and as you scroll to the top, you can't press the link

https://github.com/stakwork/sphinx-ios/assets/142233216/96486412-5c9b-4ac2-acab-dabd855e29d1
**Other devices**

- Unsure on windows or Android

**Comment by uncleJim21** [comment]
@tomastiminskas I took a look at this. It appears that it *does* work however the clickable area seems to be offset to the right (see video that proves it)

https://github.com/stakwork/sphinx-ios/assets/96802642/5d4c9969-074c-4a37-89e8-b242869d3127

**Comment by tomastiminskas** [comment]
@uncleJim21 On my tests on real device it's working perfect. No offset issues. This ticket was created before I added the LINK format and click logic on the header. So I think it can be closed

**Comment by uncleJim21** [comment]
I actually disagree. I see a significant offset when trying it on the latest build 392 on a real device. You can see that the index OfCharacter value is 0 unless it is *inside* the link's range. Which is at odds with the way you typically use this function.
https://github.com/stakwork/sphinx-ios/assets/96802642/fc1726ff-0a7f-46f0-8881-3fcee1c1d5bc

**Comment by uncleJim21** [comment]
@tomastiminskas I will add that it is necessary for you to add text *before* the link which is tacit in @tomsmith8 's experiment as well as mine.

**Comment by uncleJim21** [comment]
Closing this out as 393 addresses this
