### ISSUE TITLE
Fix adding a contact from the people site due to contact key exchange (iOS)

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-ios#290]
**Task**

Fix the issue when adding a contact from people site. The process should go like this:

1. Contact is created
2. Initial message is sent with amount (price to meet) attached

We need to make it so the message is sent once the contact was created and the encryption keys exchange was done. 

Currently, if it takes a few seconds, then the message will fail.

**Comment by ecurrencyhodler** [comment]
Closed by #304
