### ISSUE TITLE
Add "mark as unread" for a message or tribe

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-ios#305]
I would love a "mark as unread" feature for the sphinx app. This will help remind me to go back to texts and messages I receive in the sphinx tribe.

v1 doesn't have to pinpoint the exact message that I want as marked as unread. But it can simply mark the DM or Tribe group as unread.

Below is an example of what it could look like from a UI perspective taken from apple messages.

(Redacted)

**Comment by uncleJim21** [comment]
this is blocked by https://github.com/stakwork/sphinx-relay/issues/774 FYI @ecurrencyhodler
