### ISSUE TITLE
Text content is showing as hyperlinked text

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-ios#315]
Paul noticed text content showing as hyperlinked text

![Image](https://github.com/stakwork/sphinx-ios/assets/142233216/606c160d-077d-4653-89b5-80ab09aa2802)

**Comment by tomastiminskas** [comment]
@tomsmith8 couldn't find a way to reproduce it. So if you find a patter to do it please send the details. Thanks in advance

**Comment by tomsmith8** [comment]
@tomastiminskas I saw this again yesterday (on iOS) but trying to figure out the steps again. Will get back to you if I can figure them out

**Comment by tomastiminskas** [comment]
@tomsmith8 I could finally reproduce it and working on a fix. In addition I'm adding links style on threads list and thread header. Will have this included in a new release later today
