### ISSUE TITLE
Chinese and Japanese translations

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-ios#358]
**Task**

Add and translate all the strings in the app (from different files) in Japanese and Chinese. This should be applied to `localizable.string` and also to all localized storyboards and xibs.

Potential solution:
- Find all storyboard and xib files that are localized
- create a file with all the strings
- translate them
-  finally create the new files for each language with the new translated string

**Acceptance Criteria**

- [ ] Add Japanese and Chinese translations

**Comment by uncleJim21** [comment]
it is imperfect but I have a similar script that does this for spanish and tagalog. Maybe this can be a starting point? https://github.com/uncleJim21/sphinx-translations-importer-exporter

*Ideally* we had this part of CI/CD so if new terms are added we can lookup a translation even if it's not great. One can dream.

**Comment by alejandrocordon** [comment]
I can try it

**Comment by tomastiminskas** [comment]
@alejandrocordon not sure how I missed this when reviewing the PR but I was adding some strings in the localizable files and I found that Japanese and Chinese (Simplified) localizable files are not translated at all. Let me know your thoughts please

**Comment by alejandrocordon** [comment]
Done, please check my PR
