### ISSUE TITLE
Web page with instruction for Account deletion

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-ios#372]
Create a web page on Sphinx.chat 
with instruction for account deletion.

Content:
--------------

How to delete Sphinx Account

1. Open left menu (Include Screenshot)
2. Select profile (Include Screenshot)
3. Select "Advanced" tab and scroll to bottom to delete account (Include Screenshot)

Include description text to describe details about data deletion on server

**Comment by Antanasijevic** [comment]
@tomastiminskas @tomsmith8 
Current Version
https://www.sphinx.chat/how-to-delete-sphinx-account/

**Comment by tomastiminskas** [comment]
@Antanasijevic we were already unblocked from Google Play with this new webpage and the feature implemented in the app. So I think we can close this issue
