### ISSUE TITLE
Fix issue opening a jitsi call in iOS the keyboard pops up covering the controls

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-ios#373]
**Task**

When creating a jitsi call in iOS the keyboard pops up covering the controls. Only workaround is to minimize the call and then max it again to stash the keyboard.

We shouldn't pop the keyboard on iOS:

![Image](https://github.com/stakwork/sphinx-ios/assets/142233216/0aceb02a-03de-433a-948b-58f015a67605)

**Steps to recreate:**
- Be in a DM chat
- Press the call button in top right
- Open Jitsi Call
- Keyboard pops up

https://github.com/stakwork/sphinx-ios/assets/142233216/f282a927-e5b8-43d2-9a7c-576c507d6305

**Acceptance Criteria**

- [ ] Opening Jitsi call should ALWAYS stow away the keyboard

**Comment by Khaalid-oh** [comment]
I can help with this...

**Comment by patgarner** [comment]
Hi, I'd like to work on this

**Comment by uncleJim21** [comment]
Hello gentleman thank you for your interest @patgarner & @Khaalid-oh ! I actually already submitted a PR for this issue: https://github.com/stakwork/sphinx-ios/pull/374

I recommend you check out our paid bounties page and comment on the issues referenced there: https://community.sphinx.chat/bounties

Cheers,
Jim

**Comment by tomsmith8** [comment]
hey @uncleJim21 - I've just tested this and the keyboard still pops up for me. Let me know if you require any more details

https://github.com/stakwork/sphinx-ios/assets/142233216/9af046f2-f6d7-45c0-929c-0c3f8bc4ca46

**Comment by tomsmith8** [comment]
Tested on newest version - it works!
