### ISSUE TITLE
[Tests] Create UI tests on the Dashbaord view using XCUITest

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-ios#384]
### Context

The Dashbaord view is the view that shows after signing up or logging in (entering the PIN). UI Test coverage needs to be added in this view. 

**Note: Use branch `test-flight` as base branch**

Files involved:
`DashboardRootViewController.rswift`
`DashboardFeedsContainerViewController.swift`
`ChatsContainerViewController.swift`
`DiscoverTribesWebViewController.swift`
`HistoryViewController.swift`
`NewQRScannerViewController.swift`
`CreateInvoiceViewController.swift`
`Dashboard.storyboard`

The goal is to test some basic UI interactions in the Dashboard view and their expected results.

1. Add new test target to the project, XCUITest framework and any additional configuration needed to start adding UI tests (If needed/not added yet)
2. Implement the following test cases

### Dashboard View
- [ ] Tapping **Feed** tab should show feed content (DashboardFeedsContainerViewController)
- [ ] Tapping **Friends** tab should show Friends chats (ChatsContainerViewController)
- [ ] Tapping **Tribes** tab should show Tribes chats (ChatsContainerViewController)
- [ ] When on **Tribes** tab, tapping **Add Tribe** button should present Discover Tribes view (DiscoverTribesWebViewController)
- [ ] Tapping on left arrow button on bottom bar should present REQUEST AMOUNT view (CreateInvoiceViewController)
- [ ] Tapping on right arrow button on bottom bar should present Scanner View (NewQRScannerViewController)
- [ ] Tapping on scanner button on bottom bar should present Scanner View (NewQRScannerViewController)
- [ ] Tapping on transactions button on bottom bar should present Transactions View (HistoryViewController)
- [ ] When on **Friends** or **Tribes** tabs, typing on Search field should filter chat rows based on search term

**Comment by Khaalid-oh** [comment]
@SAIF
