### ISSUE TITLE
Create Tribes Tag Selection UI is Confusing

### ISSUE THREAD

**Issue by uncleJim21** [stakwork/sphinx-ios#388]
![image](https://github.com/stakwork/sphinx-ios/assets/96802642/5a6a4e64-9afe-4d95-822e-80e33cbc02b9)

When selecting tags, it is not intuitive how the user can dismiss the tribe selection modal. A simple (Done) button might be fine.

Note the shown "done" button has nothing to do with dismissing the tags modal.

**Comment by tomastiminskas** [comment]
@Antanasijevic right now you need to tap outside of the tags box to dismiss and apply new tags. Could you provide some designs for CONFIRM/CANCEL new tags selection so we can bounty this out? Thanks in advance

**Comment by Antanasijevic** [comment]
@tomastiminskas @uncleJim21 @pitoi Here is the simplest solution we could consider. 
We can reuse existing tag drawer we are using for filtering Tribes. 

Tap on tag field opens a drawer.
User selects tags, and taps "Apply". Instead of cancel button, user can just pull drawer down.
Selected tags appear in "Tag" Field.
User can remove tags by clicking X, or reopen a drawer and change selection.

What do you think?


https://github.com/stakwork/sphinx-ios/assets/13258550/385e8fbd-773f-4776-99ac-9dd729d35945

**Comment by tomastiminskas** [comment]
@tomsmith8 I would bounty this into 2 different features. 

1. Apply the same drawer we are using for filtering tribes on Discover when creating a tribe (but keep existing Tags selected UI box)
2. Apply new Tags selected box design with ability to remove one by one tapping on X button on each tag)

Let me know what do you think can I can create a ticket for items 1 with some references on the code so you can bounty it.

**Comment by tomastiminskas** [comment]
@Antanasijevic could you provide Sigma designs for the new box on create tribe form? The one that shows the selected tags and allow user to unselect by tap X button on each tag. Thanks in advance

**Comment by Antanasijevic** [comment]
@tomastiminskas @tomsmith8 Guys, here you can find final layouts (Dark and light skin), dark skin prototype and a video preview.
@tomsmith8 As a separate issue, we may consider updating input fields we are using in Sphinx. I could propose some alternatives in case you think it will be useful.

Final Figma Layout
https://www.figma.com/file/L1oq8hh8kYU90bQxPAin3G/Mobile-Design-System---Dark-Version?type=design&node-id=7577%3A9898&mode=design&t=fsdBV8piqnjUYq4F-1

Prototype (Dark Skin)
https://www.figma.com/proto/L1oq8hh8kYU90bQxPAin3G/Mobile-Design-System---Dark-Version?type=design&node-id=7582-20423&t=0gr4VqpDVsqjfG7g-1&scaling=min-zoom&page-id=7546%3A9398&starting-point-node-id=7582%3A20423&mode=design


Video Preview

https://github.com/stakwork/sphinx-ios/assets/13258550/2a14d016-b442-4bc8-a4f1-4ec0fad99517
