### ISSUE TITLE
Add Privacy Feature for balance

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-ios#396]
**Task**

Add ability to hide balance for privacy reasons:

- Tap balance at the top should turn to `*****`. Tapping again should show balance

**Code references:**
`ChatListHeaderView.xib / ChatListHeaderView.swift`
`UserDefaults.swift`

We should create a new NSUserDefaults key to store a boolean that will persist if the balance is visible or hidden. 

**Acceptance Criteria**

- [ ] Tapping a users balance at the top should hide the balance with asterisks ******

**Comment by evansmj** [comment]
Starting work on this one today

**Comment by evansmj** [comment]
pr ready for review:
https://github.com/stakwork/sphinx-ios/pull/398
