### ISSUE TITLE
Reply UX

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-ios#52]
When viewing a msg that is a reply to another msg, tapping the area of the original message clip should scroll the user up to the original message in context of the chat.  In this example, tapping "You: Fix the toolbar" would scroll the chat window back to that message.

<img width="289" alt="Screen Shot 2022-03-16 at 10 29 08 AM" src="https://user-images.githubusercontent.com/814886/158639417-feab118c-df78-4609-a43b-c756ec3c440d.png">

**Comment by jimBeaux27** [comment]
This looks fixed as of build 298
