### ISSUE TITLE
iOS: Podcast player download icon problem

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-ios#58]
When I downloaded one episode, all of the icons turned green.
Separate question: do the downloaded episodes remain on the device indefinitely? 

![IMG_8084](https://user-images.githubusercontent.com/814886/173106151-613b9a08-fca1-4df7-a57f-3e7939fc9920.PNG)

**Comment by tomastiminskas** [comment]
Download state of episodes is not being reset on cell display causing episodes state to be messed up

**Comment by jimBeaux27** [comment]
I took a stab at trying to utilize the prepareForReuse class function but it somehow causes an infinite loop :/ lol. That's usually how I solve these types of problems is to nullify images/characters after the view scrolls but that's not working here...
