### ISSUE TITLE
Indicate when payment failed

### ISSUE THREAD

**Issue by Sjors** [stakwork/sphinx-ios#6]
When I stream content but my self hosted node has routing issues, the node log will show:

```
Nov 14 08:49:42 sjimmie sphinx-relay[3908020]: KEYSEND ERROR no_route
```

But the UI doesn't indicate a problem. It does seem to catch up afterwards, at least for streaming.

This makes it difficult to know if a message or a tribe boost was actually delivered.

It's also useful to (optionally) display the exact node error message, at least for folks who self host.

**Comment by tomastiminskas** [comment]
We are now showing failed payments in transactions list with failure reason
