### ISSUE TITLE
Feed content tracking

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-ios#65]
Right now the app uses an endpoint on tribes server to get the Feed content information and store it locally using the same model structure. Previously we were fetching RSS feed data from app directly but the information coming from there was different depending on the source or the feed type, so we added tribes server in the middle to handle those differences and return to the app always the same object structure. This way adding a new content source or feed type won't need changes on all apps but changes on tribes server to match the existing models. 

`GET /feed?url=\(feedURLPath)`

We need to check the logic there to understand how each field is built, since depending on the feed type (podcast, video, newsletter) and the source of the content, the values for each attribute are built on a different way.

1. We need create a new table on apps to start tracking what users consume on feed: 
```
- FeedId - String (id of the podcast, video playlist or newsletter)
- FeedType - Int
- FeedUrl - String
- FeedItemId  - String (id of the episode, article, etc)
- FeedItemUrl - String
- StartTime - Int? (will be null for newsletter and some videos)
- EndTime - Int? (will be null for newsletter and some videos)
- Uploaded - Boolean (to track if they were sent to relay)
```

2. New endpoint on relay to send an array of `feed_tracks`. 
3. Same new table on relay

Some questions to discuss:
- What actions other than consuming content should we track? Searches? Boosts? 
- Is the FeedId and FeedItemId returned by tribes server the same we used on second brain to identify feed and feed items? Otherwise we will need to find a solution to match content on apps/relay with content on second brain.

**Comment by tomastiminskas** [comment]
Actions to be tracked

- Messages
- Content Boosts
- Podcast Clip comments
- Content consumed
- Feed Search

**Comment by tobi-bams** [comment]
## Messages
```
{
"type": "message",
"meta_data": "(Array of strings return by keyBERT)"
}
```

## Content Boosts
```
{
"type": "boost",
"meta_data": {"boost": "**boost amount**: type number",
        "date": 1601006400.0,
        "description": "The drawback to [[Taproot]]",
        "episode_title": "Payment Pools and Taproot - NADO 6",
        "guests": [],
        "image_url": "https://stakwork-uploads.s3.amazonaws.com/knowledge-graph-joe/content-images/aeb47b88-cb7f-4504-bb71-ff46d200e514.jpg",
        "keyword": true,
        "link": "https://traffic.libsyn.com/secure/nadobtc/NADO_-_Episode_6_v2.mp3?dest-id=2366201",
        "node_type": "clip",
        "ref_id": "00d21ae6-f66c-4eb3-9ee2-fe78f2f3aea4",
        "show_title": "Bitcoin Explained - The Technical Side of Bitcoin",
        "text": "different ways to actually accomplish this. Yeah. And maybe this is also a good time to bring the bad news.",
        "timestamp": "00:20:11-00:21:14",
        "topics": [
            "taproot",
            "taproot",
            "taproot"
        ],
         "type": "podcast",
        "weight": 1.5258}
},
```

## PodcastClip Comments
```
{
"type": "comment",
"meta_data": {ref_id: "Id of the podcast", link: "link to podcast", topics: "An array of strings from KetBert"]}
} 
```

## Content Consumed
```
{
"type": "content",
"meta_data": {
  "feed_id": String (id of the podcast, video playlist or newsletter)
  "feed_type": Int
   "feedUrl": String
  "feedItemId": String (id of the episode, article, etc)
  "feedItemUrl": String
  "startTime": Int? (will be null for newsletter and some videos)
  "endTime": Int? (will be null for newsletter and some videos)
  "uploaded": boolean,
  "topics": [Strings ],
  "first_interaction": unix timestamp
   "history": string["start_timestamp":0:00:01-0:00:30, "duration":number, "current_time":unix timestamp
}
}
```

## Feed Search
```
{
"type": "search",
"meta_data": {frequency: number, searched_term: string}
}
```

## Second brain consumed content
```
{
"type": "second_brain_consumed_content",
"meta_data":  {"boost": "**boost amount**: type number",
        "date": 1601006400.0,
        "description": "The drawback to [[Taproot]]",
        "episode_title": "Payment Pools and Taproot - NADO 6",
        "guests": [],
        "image_url": "https://stakwork-uploads.s3.amazonaws.com/knowledge-graph-joe/content-images/aeb47b88-cb7f-4504-bb71-ff46d200e514.jpg",
        "keyword": true,
        "link": "https://traffic.libsyn.com/secure/nadobtc/NADO_-_Episode_6_v2.mp3?dest-id=2366201",
        "node_type": "clip",
        "ref_id": "00d21ae6-f66c-4eb3-9ee2-fe78f2f3aea4",
        "show_title": "Bitcoin Explained - The Technical Side of Bitcoin",
        "text": "different ways to actually accomplish this. Yeah. And maybe this is also a good time to bring the bad news.",
        "timestamp": "00:20:11-00:21:14",
        "topics": [
            "taproot",
            "taproot",
            "taproot"
        ],
         "type": "podcast",
        "weight": 1.5258
  }
}
```

@tomastiminskas

**Comment by tomastiminskas** [comment]
@tobi-bams 

Here is an example URL of a podcast so you can check what information is available for the app to track:

https://tribes.sphinx.chat/feed?url=http://feed.nashownotes.com/rss.xml

Some questions regarding the details you posted:

## Content Boosts
`"guests"`: We just have author to complete here
`"link"`: is this link of the episode?
`"node_type": "clip"` Will be always clip?
`"ref_id": "00d21ae6-f66c-4eb3-9ee2-fe78f2f3aea4"` What is this ref-id? We have a unique id of the episode coming from tribes server
`"show_title": "Bitcoin Explained - The Technical Side of Bitcoin"` Where to take this from? We already have episode_title
`"text": "different ways to actually accomplish this. Yeah. And maybe this is also a good time to bring the bad news."`, Where to take this from? We already have description
`"topics"`: we don't have topic on the FeedContent sturcture
`"weight"`: what is this? Where to take this from?

## Content Consumed
`"topics"`: [Strings ], I don't think we have a way to get topics for any feed type
 `"first_interaction": unix timestamp` Can you explain what does it mean?
 `"history": string["start_timestamp":0:00:01-0:00:30, "duration":number, "current_time":unix timestamp` Need more details about this

## Feed Search
`"frequency"`: Would it be how many times user searched for this? as we are going to delete records after being sent to relay, I don't think we can get this information. But we can always do a count in relay for a search term. 

## Second brain consumed content
Same questions that on Content Boost

**Comment by tomastiminskas** [comment]
@tobi-bams You can use a json parser to parse the response of the url I posted before. Here is one: http://json.parser.online.fr

**Comment by tobi-bams** [comment]
@tomastiminskas 

So sorry for the mix-up, some of this fields are available only on Second Brain.
## Content Boost 
Please we would use the same field as what we have in ``Content Consumed``.

## Content Consumed
``"topics":`` I guess this is not available on the feeds endpoint, so you could skip that (@soup20 what do you think?)
``"first_interaction":`` The current time the user is interacting with the content,
``"history":`` ``start_timestamp`` is the time the user starts listening to the content(that's if it's a 5min video, did the user start at the very beginning(0 secs) or they started listening around (2min)), ``duration:`` duration of the feed(e.g podcast). 
 ``current_time:`` The current time the user is consuming the content.
 
## Feed Search
``"frequency:"`` yes this would be how many times a user searched a particular topic, if you will be maintaining a local DB, it would be good to update the frequency each time a particular topic is searched, if the searched term does not exist then frequency is 1 by default

## Second Brain Consumed Content
Please don't worry about this, it would be handled  from the Second Brain project.

**Comment by tobi-bams** [comment]
> @tobi-bams You can use a json parser to parse the response of the url I posted before. Here is one: http://json.parser.online.fr

Thanks for this man...

**Comment by tomastiminskas** [comment]
@tobi-bams so just one question regarding the `history`. 

`"history": string["start_timestamp":0:00:01-0:00:30, "duration":number, "current_time":unix timestamp`

Can you post an example of how it would be a real data set of history? Because I'm a bit confused about the format. Also I understood we are recording the `start_timestamp` the user played, but not the `end_timestamp`. I guess we should store that as well. 

Also I think `start_timestamp`, `end_timestamp` and `duration` can be of `number` type, representing seconds. What do you think?

I would suggest the following:

```
history: {
    start_timestamp: 0,
    end_timestamp: 325,
    duration: 7200,
    current_timestamp: 1663255075
}
```

**Where:** 
`start_timestamp:` 0 (means the user started playing from the beginning of the episode
`end_timestamp:` 325 (means the user finished playing at 5 minutes and 25 seconds
`duration:` 7200 (means the episode lasts 2 hours)
`current_timestamp:` 1663255075 (current unix timestamp in seconds)

**Comment by tobi-bams** [comment]
@tomastiminskas I think I agree with this...

@soup20 what's your thought on this???

**Comment by tomastiminskas** [comment]
@tobi-bams @soup20 I think what Sam described sounds good. We can make history an array of items so it will be something like this:

```
history: [
    {
        start_timestamp: 0,
        end_timestamp: 125,
        current_timestamp: 1663255075
    },
    {
        start_timestamp: 325,
        end_timestamp: 50,
        current_timestamp: 1663256085
    }
]
```

I think having `duration` and `end_timestamp` is redundant so I would remove duration. But let me know your thoughts. 

Before starting with the changes I will put everything in a new comment with the final models so we are all on the same page. I guess that will be tomorrow

**Comment by tomastiminskas** [comment]
@tobi-bams @soup20 

New table `actions`
```
 - type: Int (we can make it Int and defined each type as an enum)
 - meta_data: String (json string)
 - uploaded: Boolean (used to track if it was sent to relay)
```

Action types:
```
- Message: 0
- Feed Search: 1
- Content Boost: 2
- Podcast Clip Comment: 3
- Content Consumed: 4
```

## Message

```
"type": 0,
"meta_data": {
    "keywords" : ["bitcoin", "lightning", "sphinx"]
},
"uploaded": false
```

## Feed Search
```
"type": 1,
"meta_data": {
    "frequency": 1, 
    "search_term": "bitcoin"
},
"uploaded": false
```

## Content Boost
```
"type": 2,
"meta_data": {
    "boost": 1000,
    "feed_id": "41504" (id of the podcast, video playlist or newsletter),
    "feed_type": 0 (Podcast, Video, Newsletter),
    "feed_url": "http://feed.nashownotes.com/rss.xml",
    "feed_item_id": "10226884597" (id of the episode, article, etc),
    "feed_item_url": "https://mp3s.nashownotes.com/NA-1487-2022-09-18-Final.mp3",
    "topics": []
},
"uploaded": false
```

## Podcast Clip Comment
```
"type": 3,
"meta_data": {
    "feed_id": "41504" (id of the podcast, video playlist or newsletter),
    "feed_type": 0 (Podcast, Video, Newsletter),
    "feed_url": "http://feed.nashownotes.com/rss.xml",
    "feed_item_id": "10226884597" (id of the episode, article, etc),
    "feed_item_url": "https://mp3s.nashownotes.com/NA-1487-2022-09-18-Final.mp3",
    "topics": [],
    "start_timestamp": 0 (seconds),
    "end_timestamp": 125 (seconds),
    "current_timestamp": 1663255075,
},
"uploaded": false
```

## Content Consumed
```
"type": 4,
"meta_data": {
    "feed_id": "41504" (id of the podcast, video playlist or newsletter),
    "feed_type": 0 (Podcast, Video, Newsletter),
    "feed_url": "http://feed.nashownotes.com/rss.xml",
    "feed_item_id": "10226884597" (id of the episode, article, etc),
    "feed_item_url": "https://mp3s.nashownotes.com/NA-1487-2022-09-18-Final.mp3",
    "topics": EMPTY FOR NOW,
    "first_interaction": 1663255075 (unix timestamp),
    "history": [
        {
            "start_timestamp": 0 (seconds),
            "end_timestamp": 125 (seconds),
            "current_timestamp": 1663255075
        },
        {
            "start_timestamp": 325 (seconds),
            "end_timestamp": 50 (seconds),
            "current_timestamp": 1663256085
        }
    ]
},
"uploaded": false
```

**Comment by tomastiminskas** [comment]
@tobi-bams @soup20 we made good progress on these changes on both iOS and android apps and even when we still need to figure out how to integrate keyBERT for keywords extraction on both I think it's a good moment to work on the relay endpoint to start testing the process of sending the tracked actions to relay.

So basically we need a `POST` endpoint that receives an `array of actions` (with `type` and `meta_data` each one). With that endpoint we can work on a background process that will send them in batches.

Let me know if it makes sense to you and if you can coordinate the work.

**Comment by tobi-bams** [comment]
@tomastiminskas @soup20 the save-bulk-action-history endpoint is available on this [https://github.com/stakwork/sphinx-relay/pull/424] branch on sphinx-relay, I have created a PR already

the endpoint is called `/action_history_bulk”`

Here is an example of the request body

```
{
    "data": [
        {
            "type": "boost",
            "meta_data": {
                "boost": 0,
                "date": 1601006400.0,
                "description": "The drawback to [[Taproot]]",
                "episode_title": "Payment Pools and Taproot - NADO 6",
                "guests": [],
                "image_url": "https://stakwork-uploads.s3.amazonaws.com/knowledge-graph-joe/content-images/aeb47b88-cb7f-4504-bb71-ff46d200e514.jpg",
                "keyword": true,
                "link": "https://traffic.libsyn.com/secure/nadobtc/NADO_-_Episode_6_v2.mp3?dest-id=2366201",
                "node_type": "clip",
                "ref_id": "00d21ae6-f66c-4eb3-9ee2-fe78f2f3aea4",
                "show_title": "Bitcoin Explained - The Technical Side of Bitcoin",
                "text": "different ways to actually accomplish this. Yeah. And maybe this is also a good time to bring the bad news. There really isn't any working system out there yet that does this partially because we still need Taproot because it just makes it otherwise it's not terribly useful. Yeah. It's built on Taproot That's where the benefits of the private updates come from. Am I saying that right? Yeah, I think so. Like the collaborative updates of the state of the pool. So whatever the pool is can update without revealing the update, especially if everybody agrees. Then it's very nice, this tapworth feature that uses shore, where you can combine signatures and make it look like one signature, because otherwise if you have three participants, you could make a pool without Taproot. But every time you do something at the pool, it's completely obvious how many people there are in the pool and what they're doing. Yeah. So basically there are three different designs. Yeah, I say. So let's start with the first one or ",
                "timestamp": "00:20:11-00:21:14"
            }
        },
      
    ]
}
```

**Comment by tomastiminskas** [comment]
@tobi-bams @soup20 I was testing the endpoint and I could make it to work on iOS. I checked the db on my node and the actions are being inserted. The only thing that I noticed and I'm not sure if we should change is the type of the `type` column on relay. On all apps it's an integer representing these values:

```
- Message: 0
- Feed Search: 1
- Content Boost: 2
- Podcast Clip Comment: 3
- Content Consumed: 4
```

But on relay it is a VARCHAR(255) so I'm not sure what should we do:
- Define a name for each type and send it from the app as a string `("boost", "message", etc)`
- Send an integer from app to be stored as a string on relay db `("0", "1", etc)`
- Change the column type to int and store the integer value. `(0, 1, etc)`. I think this third option is the right now to improve performance when querying the db later, but it will need changes on relay

**Comment by tomastiminskas** [comment]
@soup20 @tobi-bams any news on this? I want to test the new column before uploading a version for internal testing. 

I would need the changes to be deployed to my nodes to test it

**Comment by tobi-bams** [comment]
@tomastiminskas the changes have been implemented, I also informed Kevin to update your node, I don't know if he has done that already...

Lemme ask him

**Comment by tomastiminskas** [comment]
@soup20 @tobi-bams Also I tried to test on Tom Device node and the endpoint is always returning failure. I checked the logs and it seems because the ID can not be null. When I checked the schema of the new table on both TOM DEVICE and TOM SIM nodes I found big differences (not sure why):


TOM DEVICE:
```
sqlite> .schema sphinx_action_history
CREATE TABLE sphinx_action_history (
      id BIGINT NOT NULL PRIMARY KEY,
      type TEXT,
      meta_data TEXT,
      tenant INTEGER,
			created_at DATETIME,
      updated_at DATETIME
    );
```

TOM SIM
```
sqlite> .schema sphinx_action_history
CREATE TABLE `sphinx_action_history` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `type` VARCHAR(255), `meta_data` TEXT, `tenant` INTEGER, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL);
```

On Tom Device the id is not `AUTOINCREMENT` causing the insert to fail because of a NULL id. And there are other differences on the schema (id type, type column type, created_at and updated_at nullability, etc). Not sure which one is the right now so I can't test and confirm it's working before uploading version to internal testing
