### ISSUE TITLE
Mentions autocomplete

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-ios#69]
- Start caching aliases of tribe members when receiving messages on a tribe you are in
- When typing @ character, use the cached aliases to suggest and autocomplete the mention.

**Comment by tomastiminskas** [comment]
@Antanasijevic we might need some designs for how to show autocomplete or suggestions when typing a mention (not urgent)

**Comment by tomastiminskas** [comment]
1. Create new field on Chat model: aliases - Transformable ([String] - Array of Strings) and start saving sender_alias of each messages received on a tribe
2. When typing a message, if user types an @ and the first letter after it, show a list of suggestions over the field message with the tribe aliases on that tribe matching the letters entered. Allow to select an option tapping on it or using tab key.

**Comment by jimBeaux27** [comment]
Ok I'm on this @tomastiminskas

**Comment by tomastiminskas** [comment]
Hey @jimBeaux27 I will be reviewing and testing the changes tomorrow and I will let you know how it goes. Please next time keep in mind that you need to tap on "I can help" button on https://people.sphinx.chat/tickets and and ask the ticket creator on Sphinx so he can assign it to you. Otherwise 2 people can be working on the same task at the same time (what actually happens in this case)

Also let me know your username on people site so I can assign it to you now. Thanks in advance

**Comment by jimBeaux27** [comment]
ok my username is the same on Sphinx as jimBeaux27
