### ISSUE TITLE
Attempting to Enter Sphinx Chat for Newly Joined Tribe

### ISSUE THREAD

**Issue by uncleJim21** [stakwork/sphinx-ios#76]
Trying to enter newly joined Tribe (Tales From the Crypt) causes my iOS client to crash (but not Mac).

Here's what I'm observing:
- Successfully joined the tribe and paid the sats
- Tribe appears in my Tribe UITableView
- When I click on the TFTC cell, immediately crashes and I get these messages:

![image](https://user-images.githubusercontent.com/96802642/205992694-5179f5e2-e2cf-4688-bb37-ddec670ef548.png)

![image](https://user-images.githubusercontent.com/96802642/205992819-66d090f7-4133-4710-b0ac-631adae32edc.png)

Looks like this BTC-Principle color is causing a malfunction when doing a lookup in UserDefaults:
![image](https://user-images.githubusercontent.com/96802642/205993640-3d4a4a1c-f43f-40ec-8e56-df325310afbb.png)

**Comment by jimBeaux27** [comment]
@pitoi @kevkevinpal @tomastiminskas I seem to have fixed this by doing the following:
`


static func getColorFor(key: String) -> UIColor {
        
        if let colorCode = UserDefaults.standard.string(forKey: key){
            return UIColor(hex: colorCode)
        } else {
            let newColor = UIColor.random()
            UserDefaults.standard.set(newColor.toHexString(), forKey: key)
            UserDefaults.standard.synchronize()
            return newColor
        }
    }

`

Shall I submit a PR?

**Comment by jimBeaux27** [comment]
I went ahead and submitted a PR anyway https://github.com/stakwork/sphinx-ios/pull/77
