### ISSUE TITLE
Badges: badge creation display for tribe admins - iOS

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-ios#87]
Tribe admins will be able to create badges for their tribe. They will have a tribe badge inventory, showing all the existing badges for their tribe. When they create badges, they will select:
- badge title
- badge icon
- requirements to achieve badge
- quantity of that badge to create

Here is the Figma (look at Tribe Badges section):
[https://www.figma.com/file/L1oq8hh8kYU90bQxPAin3G/Mobile-Design-System---Dark-Version?node-id=0%3A1&t=4GT2Y7QjhFdwBb3y-0](url)

Here is the video:
https://user-images.githubusercontent.com/104323003/209407135-4f5cb520-1d9c-4f66-801f-c40edcfdd6a6.mp4

When the admin hits create badges, app should hit this endpoint on relay:
`${base_url}/create_badge`

With this request body:
```
{
 "icon": "string", (icon link)
 "name": "string", (badge title)
 "amount": int, (quantity of badges to be created)
 "chat_id": int,
 "claim_amount": int,
 "reward_type": int
}
```

**Comment by tomastiminskas** [comment]
@soup20 I was just taking a look at this to see if I could have Alejandro starting working on the layouts on android but the video is not playing at all for me. On any case it will be needed to have the designs in Sigma if possible so we can take details from there. Finally I saw that you created the same ticket on sphinx-kotlin-core but I think you wanted to create it on sphinx-kotlin (which is the android repo)

**Comment by jimBeaux27** [comment]
@soup20 @tomastiminskas hey guys I am taking this on and did some research on the spec. Here are my notes on most of the things that need to happen as well as some open questions on the API/Model spec:

To Do List:
  **UI:**
      1. Entry point for badge interface from GroupInfoVC (admin only)
      2. Read existing badges (populates tableview)
      3. Create a new badge -> entry point to this interface is where? (+ button above tableView??)
      4. Update badge -> click on tableView to see specific badge, change items
          1. Probably want to reuse the UI for create/update and just vary slightly
      5. Delete badge -> swipe action? Or delete from “show”/update screen for specific badge
  
  **Model:**
  Probably best to have a model that captures
      1. Icon
      2. Amount
      3. Name
      4. chat_id
      5. claim_amount
      6. reward_type
      7. Number of total badges available??
      8. Number of total badges issued??
  
  **API:**
  Need to create and use endpoints for all CRUD actions
      1. Create
      2. Read
      3. Update
      4. Delete
  
  
  **Open Questions:**
  1. What are the endpoints for the R,U,D actions?
  2. Where exactly do we store the badge images when we create? The spec says it’s a link but where should that link go?
  3. What additional fields are necessary for the model to make this work smoothly? I think I found 2 in 7 and 8 above

**Comment by tomastiminskas** [comment]
@jimBeaux27 great research and description of what's defined and what's missing. Let's start building the UI and wait for @soup20 to be back. Then we can jump on a call all together and defined what we are missing to work on the logic

**Comment by jimBeaux27** [comment]
Roger that @tomastiminskas🫡

**Comment by jimBeaux27** [comment]
@tomastiminskas @soup20 I got pretty far along on this on iOS see https://github.com/jimBeaux27/sphinx-ios/tree/jc/develop/admin-badges. Aside from a few UI tweaks that are inevitable we're pretty much ready to start integrating the services/API layers.

**Comment by tomastiminskas** [comment]
@soup20 any updates on server side changes for this? Jim has the UI ready to start working on the logic. Maybe a call tomorrow or Monday to catch up and see how we continue?

**Comment by tomastiminskas** [comment]
Issues on Tribe Badges: @jimBeaux27 

![IMG_0287](https://user-images.githubusercontent.com/2242281/220964721-a08ca39f-84a0-4386-b8a2-3086f726b11a.jpg)

Toggle should be aligned to right edge

![IMG_0286](https://user-images.githubusercontent.com/2242281/220964800-7eb9047d-7849-4ea8-8c86-fe31a93d032c.jpg)

The dark back of the amount control is slightly exceeding the gray circle (should be adjusted as it is in the right grey circle)

![IMG_0285](https://user-images.githubusercontent.com/2242281/220965029-367a78c6-aea9-4392-b038-49372971bf8c.jpg)

The title of the MANAGE EXISTING BADGES should be aligned to the left and should have a different UI to be more distinguishable. Maybe SecondaryText for font color or something like that

https://user-images.githubusercontent.com/2242281/220965468-eab1dbe2-a3b4-414a-9a05-84285c469a62.MP4

Purchasing a badge is throwing an error even when it worked.

**Comment by jimBeaux27** [comment]
RE: MANAGE EXISTING BADGES label. It is aligned to be te same indent as Create New Badge. I don't think we should move it left.

Let me know what color we actually want it to be and I can do it but imo it is on the same footing hierarchy as create so it should remain as is.
